version: '3.8'

services:
  app:
    build: .
    command: 'npm run dev'
    depends_on:
       - postgres
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - './package.json:/service/package.json'
      - './package-lock.json:/service/package-lock.json'
      - './public:/service/public'
      - './src:/service/src'
      - './prisma:/service/prisma'

  postgres:
     image: postgres:14
     environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'database'
      POSTGRES_DB: 'identity_challenge'
     ports:
       - "5432:5432"
     volumes:
       - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: